# =============================================================================
# CANONICAL SKILLS — master list of recognized skills across all domains
# =============================================================================

CANONICAL_SKILLS = [
    # ── IT / Software ──────────────────────────────────────────────────────
    "Python",
    "FastAPI",
    "Django",
    "Flask",
    "JavaScript",
    "TypeScript",
    "React",
    "Node.js",
    "SQL",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "GCP",
    "Git",
    "CI/CD",
    "Machine Learning",
    "Deep Learning",
    "NLP",
    "Pandas",
    "NumPy",
    "PyTorch",
    "TensorFlow",
    "REST API",
    "Microservices",
    # ── Construction ───────────────────────────────────────────────────────
    "bricklaying",
    "plastering",
    "carpentry",
    "joinery",
    "scaffolding",
    "concreting",
    "groundwork",
    "demolition",
    "roofing",
    "tiling",
    "painting and decorating",
    "plumbing",
    "electrical work",
    "welding",
    "plant operation",
    "construction labour",
    "site management",
    "construction project experience",
    "working at heights",
    "health and safety",
    "CPCS certification",
    "CSCS card",
    "first aid",
    "manual handling",
    "asbestos awareness",
    "confined space working",
    "excavation",
    "formwork",
    "steel fixing",
    "drainage installation",
    "road construction",
    "surveying",
    "quantity surveying",
    "site supervision",
    "blueprint reading",
    "AutoCAD",
    "BIM",
    "electrical work support",
    "plumbing support",
    "joinery support",
    # ── Driving / Transport / Logistics ────────────────────────────────────
    "driving licence",
    "HGV licence",
    "forklift operation",
    "reach truck operation",
    "counterbalance forklift",
    "pallet truck operation",
    "vehicle loading",
    "route planning",
    "fleet management",
    "tachograph operation",
    "ADR certification",
    "CPC qualification",
    "logistics coordination",
    "stock control",
    "inventory management",
    "goods receiving",
    "dispatch",
    "warehouse management",
    "order picking",
    "packing",
    "goods-in",
    "goods-out",
    "delivery driving",
    "van driving",
    "LGV driving",
    # ── Warehouse ──────────────────────────────────────────────────────────
    "warehouse operations",
    "pick and pack",
    "RF scanning",
    "barcode scanning",
    "stock replenishment",
    "cycle counting",
    "FIFO",
    "LIFO",
    "WMS",
    "SAP",
    "ERP",
    "goods receipt",
    "quality control",
    "returns processing",
    # ── Retail / Customer Service ──────────────────────────────────────────
    "customer service",
    "cash handling",
    "POS systems",
    "stock management",
    "visual merchandising",
    "sales",
    "upselling",
    "complaint handling",
    "till operation",
    "retail operations",
    "product knowledge",
    "EPOS",
    # ── Manufacturing ──────────────────────────────────────────────────────
    "machine operation",
    "CNC operation",
    "lathe operation",
    "milling",
    "assembly line",
    "quality assurance",
    "lean manufacturing",
    "5S",
    "Six Sigma",
    "production planning",
    "maintenance",
    "hydraulics",
    "pneumatics",
    "PLC programming",
    "health and safety compliance",
    "PPE usage",
    "risk assessment",
    # ── Mechanics / Automotive ─────────────────────────────────────────────
    "vehicle diagnostics",
    "brake system repair",
    "engine repair",
    "MOT testing",
    "tyre fitting",
    "wheel alignment",
    "oil change",
    "transmission repair",
    "electrical diagnostics",
    "bodywork repair",
    "vehicle inspection",
    "fault finding",
    "diagnostic tools",
    "vehicle servicing",
    # ── Administration / Office ────────────────────────────────────────────
    "Microsoft Office",
    "Microsoft Excel",
    "Microsoft Word",
    "Microsoft PowerPoint",
    "data entry",
    "filing",
    "scheduling",
    "minute taking",
    "report writing",
    "bookkeeping",
    "accounts payable",
    "accounts receivable",
    "payroll",
    "HR administration",
    "recruitment",
    "project management",
    "GDPR compliance",
    "CRM systems",
    "Salesforce",
    "Sage",
    "Xero",
    "QuickBooks",
]

# =============================================================================
# SKILL SYNONYMS — maps any surface form → canonical skill name
# All keys MUST be lowercase.
# =============================================================================

SKILL_SYNONYMS: dict[str, str] = {
    # ── IT (existing) ──────────────────────────────────────────────────────
    "js": "JavaScript",
    "javascript": "JavaScript",
    "ts": "TypeScript",
    "typescript": "TypeScript",
    "sql": "SQL",
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "ml": "Machine Learning",
    "machine learning": "Machine Learning",
    "uczenie maszynowe": "Machine Learning",
    "sztuczna inteligencja": "Machine Learning",
    "ai": "Machine Learning",
    "głębokie uczenie": "Deep Learning",
    "deep learning": "Deep Learning",
    "nlp": "NLP",
    "przetwarzanie języka naturalnego": "NLP",
    "rest": "REST API",
    "rest api": "REST API",
    "mikroserwisy": "Microservices",
    "microservices": "Microservices",
    "konteneryzacja": "Docker",
    "docker": "Docker",
    "k8s": "Kubernetes",
    "kubernetes": "Kubernetes",
    "chmura aws": "AWS",
    "aws": "AWS",
    "azure": "Azure",
    "gcp": "GCP",
    "git": "Git",
    "ci/cd": "CI/CD",
    "fast api": "FastAPI",
    "fastapi": "FastAPI",
    "react.js": "React",
    "react": "React",
    "node": "Node.js",
    "nodejs": "Node.js",
    "node.js": "Node.js",
    # ── Construction — job titles / roles ──────────────────────────────────
    "plant operator": "plant operation",
    "plant operative": "plant operation",
    "plant operations": "plant operation",
    "heavy plant operator": "plant operation",
    "construction plant operator": "plant operation",
    "plant machinery operator": "plant operation",
    "heavy machinery operation": "plant operation",
    "heavy machinery operator": "plant operation",
    "labourer": "construction labour",
    "laborer": "construction labour",
    "general labourer": "construction labour",
    "construction labourer": "construction labour",
    "construction laborer": "construction labour",
    "construction worker": "construction labour",
    "general construction worker": "construction labour",
    "site labourer": "construction labour",
    "bricklayer": "bricklaying",
    "brick layer": "bricklaying",
    "brick laying": "bricklaying",
    "bricklaying work": "bricklaying",
    "brickwork": "bricklaying",
    "plasterer": "plastering",
    "plastering work": "plastering",
    "carpenter": "carpentry",
    "carpentry work": "carpentry",
    "joiner": "joinery",
    "joinery work": "joinery",
    "joinery support": "joinery support",
    "assisted joiners": "joinery support",
    "scaffolder": "scaffolding",
    "scaffolding work": "scaffolding",
    "roofer": "roofing",
    "roofing work": "roofing",
    "tiler": "tiling",
    "tiling work": "tiling",
    "painter": "painting and decorating",
    "decorator": "painting and decorating",
    "painter and decorator": "painting and decorating",
    "painting & decorating": "painting and decorating",
    "welder": "welding",
    "welding work": "welding",
    "groundworker": "groundwork",
    "groundworks": "groundwork",
    "site manager": "site management",
    "site supervisor": "site supervision",
    "construction projects": "construction project experience",
    "construction project": "construction project experience",
    "worked on construction projects": "construction project experience",
    # ── Construction — health & safety ────────────────────────────────────
    "health and safety": "health and safety",
    "health & safety": "health and safety",
    "h&s": "health and safety",
    "site safety": "health and safety",
    "health and safety award": "health and safety",
    "health & safety award": "health and safety",
    "health and safety certificate": "health and safety",
    "health and safety training": "health and safety",
    "health and safety compliance": "health and safety compliance",
    "ppe usage": "PPE usage",
    "ppe": "PPE usage",
    "personal protective equipment": "PPE usage",
    "risk assessment": "risk assessment",
    "risk assessments": "risk assessment",
    "manual handling": "manual handling",
    "manual handling certificate": "manual handling",
    "manual handling training": "manual handling",
    "first aid": "first aid",
    "first aid certificate": "first aid",
    "first aid at work": "first aid",
    "asbestos awareness": "asbestos awareness",
    "asbestos awareness certificate": "asbestos awareness",
    "confined space": "confined space working",
    "confined spaces": "confined space working",
    "working at heights": "working at heights",
    "worked at heights": "working at heights",
    "work at height": "working at heights",
    "working at height": "working at heights",
    "height safety": "working at heights",
    # ── Construction — certifications / licences ───────────────────────────
    "cpcs licence": "CPCS certification",
    "cpcs license": "CPCS certification",
    "cpcs card": "CPCS certification",
    "cpcs certification": "CPCS certification",
    "cpcs": "CPCS certification",
    "construction plant competence scheme": "CPCS certification",
    "cscs card": "CSCS card",
    "cscs": "CSCS card",
    "construction skills certification scheme": "CSCS card",
    "nvq construction": "construction labour",
    "nvq bricklaying": "bricklaying",
    # ── Construction — trades support ─────────────────────────────────────
    "assisted electricians": "electrical work support",
    "assisting electricians": "electrical work support",
    "electrical work support": "electrical work support",
    "electrical support": "electrical work support",
    "assisted plumbers": "plumbing support",
    "assisting plumbers": "plumbing support",
    "plumbing support": "plumbing support",
    "plumbing work": "plumbing",
    "plumber": "plumbing",
    "electrician": "electrical work",
    "electrical work": "electrical work",
    "assisted joiners": "joinery support",
    "assisting joiners": "joinery support",
    # ── Driving / Transport ────────────────────────────────────────────────
    "driving licence": "driving licence",
    "driving license": "driving licence",
    "driver licence": "driving licence",
    "driver license": "driving licence",
    "full uk driving licence": "driving licence",
    "full driving licence": "driving licence",
    "clean driving licence": "driving licence",
    "valid driving licence": "driving licence",
    "cat b licence": "driving licence",
    "category b licence": "driving licence",
    "hgv licence": "HGV licence",
    "hgv license": "HGV licence",
    "hgv driver": "HGV licence",
    "lgv licence": "LGV driving",
    "lgv driver": "LGV driving",
    "van driver": "van driving",
    "delivery driver": "delivery driving",
    "forklift": "forklift operation",
    "forklift truck": "forklift operation",
    "forklift operator": "forklift operation",
    "forklift licence": "forklift operation",
    "counterbalance": "counterbalance forklift",
    "reach truck": "reach truck operation",
    "pallet truck": "pallet truck operation",
    "pump truck": "pallet truck operation",
    # ── Warehouse ──────────────────────────────────────────────────────────
    "warehouse": "warehouse operations",
    "warehouse operative": "warehouse operations",
    "warehouse worker": "warehouse operations",
    "warehouse assistant": "warehouse operations",
    "pick and pack": "pick and pack",
    "picking and packing": "pick and pack",
    "order picking": "order picking",
    "order picker": "order picking",
    "packing": "packing",
    "goods receiving": "goods receiving",
    "goods receipt": "goods receipt",
    "goods in": "goods-in",
    "goods out": "goods-out",
    "dispatch": "dispatch",
    "stock control": "stock control",
    "stock management": "stock management",
    "inventory management": "inventory management",
    "inventory control": "inventory management",
    "stock replenishment": "stock replenishment",
    "rf scanning": "RF scanning",
    "rf gun": "RF scanning",
    "barcode scanning": "barcode scanning",
    "barcode scanner": "barcode scanning",
    "wms": "WMS",
    "warehouse management system": "WMS",
    "sap": "SAP",
    "erp": "ERP",
    "cycle counting": "cycle counting",
    "stock take": "cycle counting",
    "stocktaking": "cycle counting",
    "returns processing": "returns processing",
    "returns": "returns processing",
    # ── Retail / Customer Service ──────────────────────────────────────────
    "customer service": "customer service",
    "customer services": "customer service",
    "customer support": "customer service",
    "customer care": "customer service",
    "cash handling": "cash handling",
    "cash register": "cash handling",
    "till": "till operation",
    "till operation": "till operation",
    "pos": "POS systems",
    "pos system": "POS systems",
    "epos": "EPOS",
    "sales assistant": "sales",
    "retail assistant": "retail operations",
    "retail": "retail operations",
    "retail worker": "retail operations",
    "visual merchandising": "visual merchandising",
    "merchandising": "visual merchandising",
    "upselling": "upselling",
    "cross-selling": "upselling",
    "complaint handling": "complaint handling",
    "complaints handling": "complaint handling",
    "handling complaints": "complaint handling",
    # ── Manufacturing ──────────────────────────────────────────────────────
    "machine operator": "machine operation",
    "machine operative": "machine operation",
    "machine operation": "machine operation",
    "cnc": "CNC operation",
    "cnc operator": "CNC operation",
    "cnc machinist": "CNC operation",
    "lathe": "lathe operation",
    "lathe operator": "lathe operation",
    "milling": "milling",
    "milling machine": "milling",
    "assembly": "assembly line",
    "assembly line": "assembly line",
    "production line": "assembly line",
    "production operative": "assembly line",
    "lean": "lean manufacturing",
    "lean manufacturing": "lean manufacturing",
    "5s": "5S",
    "six sigma": "Six Sigma",
    "6 sigma": "Six Sigma",
    "quality control": "quality control",
    "qc": "quality control",
    "quality assurance": "quality assurance",
    "qa": "quality assurance",
    "production planning": "production planning",
    "maintenance engineer": "maintenance",
    "maintenance technician": "maintenance",
    "maintenance": "maintenance",
    "hydraulics": "hydraulics",
    "pneumatics": "pneumatics",
    "plc": "PLC programming",
    "plc programming": "PLC programming",
    # ── Mechanics / Automotive (English) ──────────────────────────────────
    "vehicle diagnostics": "vehicle diagnostics",
    "car diagnostics": "vehicle diagnostics",
    "diagnostic": "vehicle diagnostics",
    "diagnostics": "vehicle diagnostics",
    "brake repair": "brake system repair",
    "brakes": "brake system repair",
    "brake system": "brake system repair",
    "engine repair": "engine repair",
    "engine work": "engine repair",
    "mot": "MOT testing",
    "mot testing": "MOT testing",
    "mot tester": "MOT testing",
    "tyre fitting": "tyre fitting",
    "tyres": "tyre fitting",
    "wheel alignment": "wheel alignment",
    "tracking": "wheel alignment",
    "oil change": "oil change",
    "servicing": "vehicle servicing",
    "vehicle servicing": "vehicle servicing",
    "car servicing": "vehicle servicing",
    "transmission": "transmission repair",
    "gearbox": "transmission repair",
    "bodywork": "bodywork repair",
    "body repair": "bodywork repair",
    "vehicle inspection": "vehicle inspection",
    "fault finding": "fault finding",
    "fault diagnosis": "fault finding",
    # ── Mechanics / Automotive (English — additional) ──────────────────────
    "automotive mechanic": "vehicle servicing",
    "automotive technician": "vehicle servicing",
    "automotive engineer": "vehicle servicing",
    "automotive repair": "engine repair",
    "technical assistant automotive": "vehicle servicing",
    "auto mechanic": "vehicle servicing",
    "car mechanic": "vehicle servicing",
    "vehicle maintenance": "vehicle servicing",
    "vehicle repair": "engine repair",
    "workshop tools usage": "vehicle servicing",
    "workshop tools": "vehicle servicing",
    "car repair": "engine repair",
    "car maintenance": "vehicle servicing",
    "motor mechanic": "vehicle servicing",
    "motor vehicle technician": "vehicle servicing",
    "light vehicle technician": "vehicle servicing",
    "heavy vehicle technician": "vehicle servicing",
    # ── Mechanics / Automotive (Polish) ───────────────────────────────────
    "mechanik": "vehicle servicing",
    "mechanik samochodowy": "vehicle servicing",
    "mechanik pojazdów": "vehicle servicing",
    "mechanik pojazdów samochodowych": "vehicle servicing",
    "mechanik pojazdów ciężarowych": "vehicle servicing",
    "technik mechanik": "vehicle servicing",
    "technik pojazdów samochodowych": "vehicle servicing",
    "naprawa aut": "engine repair",
    "naprawa samochodów": "engine repair",
    "naprawa pojazdów": "engine repair",
    "naprawa silnika": "engine repair",
    "naprawa silników": "engine repair",
    "diagnostyka": "vehicle diagnostics",
    "diagnostyka auta": "vehicle diagnostics",
    "diagnostyka pojazdu": "vehicle diagnostics",
    "diagnostyka pojazdów": "vehicle diagnostics",
    "diagnostyka samochodowa": "vehicle diagnostics",
    "diagnostyka komputerowa": "vehicle diagnostics",
    "serwis samochodowy": "vehicle servicing",
    "serwis pojazdów": "vehicle servicing",
    "przegląd techniczny": "vehicle inspection",
    "przegląd pojazdu": "vehicle inspection",
    "wymiana oleju": "oil change",
    "wymiana olejów": "oil change",
    "hamulce": "brake system repair",
    "naprawa hamulców": "brake system repair",
    "układ hamulcowy": "brake system repair",
    "skrzynia biegów": "transmission repair",
    "naprawa skrzyni biegów": "transmission repair",
    "elektryk samochodowy": "electrical diagnostics",
    "instalacja elektryczna": "electrical diagnostics",
    "blacharstwo": "bodywork repair",
    "blacharstwo samochodowe": "bodywork repair",
    "lakiernictwo": "bodywork repair",
    "lakiernictwo samochodowe": "bodywork repair",
    "wulkanizacja": "tyre fitting",
    "wymiana opon": "tyre fitting",
    "geometria kół": "wheel alignment",
    "ustawianie geometrii": "wheel alignment",
    "zawieszenie": "vehicle servicing",
    "układ kierowniczy": "vehicle servicing",
    "silnik": "engine repair",
    "naprawa silnika spalinowego": "engine repair",
    # ── Construction (Polish) ─────────────────────────────────────────────
    "budowlaniec": "construction labour",
    "pracownik budowlany": "construction labour",
    "robotnik budowlany": "construction labour",
    "praca na budowie": "construction labour",
    "prace budowlane": "construction labour",
    "roboty budowlane": "construction labour",
    "prace fizyczne": "manual handling",
    "praca fizyczna": "manual handling",
    "murarz": "bricklaying",
    "murarstwo": "bricklaying",
    "tynkarz": "plastering",
    "tynkowanie": "plastering",
    "cieśla": "carpentry",
    "ciesielstwo": "carpentry",
    "stolarz": "joinery",
    "stolarstwo": "joinery",
    "spawacz": "welding",
    "spawanie": "welding",
    "elektryk": "electrical work",
    "prace elektryczne": "electrical work",
    "hydraulik": "plumbing",
    "instalacje hydrauliczne": "plumbing",
    "dekarz": "roofing",
    "dekarstwo": "roofing",
    "glazurnik": "tiling",
    "układanie glazury": "tiling",
    "malarz": "painting and decorating",
    "malowanie": "painting and decorating",
    "bhp": "health and safety",
    "bezpieczeństwo i higiena pracy": "health and safety",
    "bezpieczeństwo pracy": "health and safety",
    "praca na wysokości": "working at heights",
    "prace na wysokości": "working at heights",
    "obsługa maszyn": "machine operation",
    "obsługa maszyn budowlanych": "plant operation",
    "wózek widłowy": "forklift operation",
    "obsługa wózka widłowego": "forklift operation",
    "operator wózka widłowego": "forklift operation",
    # ── Warehouse / Logistics (Polish) ────────────────────────────────────
    "magazynier": "warehouse operations",
    "pracownik magazynu": "warehouse operations",
    "pracownik magazynowy": "warehouse operations",
    "kompletacja zamówień": "order picking",
    "kompletowanie zamówień": "order picking",
    "przyjęcie towaru": "goods receiving",
    "przyjmowanie towaru": "goods receiving",
    "wysyłka": "dispatch",
    "wysyłka towaru": "dispatch",
    "kontrola zapasów": "stock control",
    "zarządzanie zapasami": "inventory management",
    "gospodarka magazynowa": "warehouse operations",
    # ── General (Polish) ──────────────────────────────────────────────────
    "prawo jazdy": "driving licence",
    "prawo jazdy kat. b": "driving licence",
    "prawo jazdy kategorii b": "driving licence",
    "prawo jazdy kat b": "driving licence",
    "pierwsza pomoc": "first aid",
    "obsługa komputera": "Microsoft Office",
    "pakiet office": "Microsoft Office",
    "ms office": "Microsoft Office",
    "obsługa ms office": "Microsoft Office",
    "wprowadzanie danych": "data entry",
    "obsługa kasy": "cash handling",
    "obsługa klienta": "customer service",
    # ── Administration / Office ────────────────────────────────────────────
    "microsoft office": "Microsoft Office",
    "ms office": "Microsoft Office",
    "office suite": "Microsoft Office",
    "excel": "Microsoft Excel",
    "microsoft excel": "Microsoft Excel",
    "ms excel": "Microsoft Excel",
    "word": "Microsoft Word",
    "microsoft word": "Microsoft Word",
    "ms word": "Microsoft Word",
    "powerpoint": "Microsoft PowerPoint",
    "microsoft powerpoint": "Microsoft PowerPoint",
    "ms powerpoint": "Microsoft PowerPoint",
    "data entry": "data entry",
    "data input": "data entry",
    "typing": "data entry",
    "filing": "filing",
    "scheduling": "scheduling",
    "diary management": "scheduling",
    "minute taking": "minute taking",
    "minutes": "minute taking",
    "report writing": "report writing",
    "bookkeeping": "bookkeeping",
    "book keeping": "bookkeeping",
    "accounts payable": "accounts payable",
    "accounts receivable": "accounts receivable",
    "payroll": "payroll",
    "hr": "HR administration",
    "human resources": "HR administration",
    "hr administration": "HR administration",
    "recruitment": "recruitment",
    "project management": "project management",
    "pm": "project management",
    "gdpr": "GDPR compliance",
    "gdpr compliance": "GDPR compliance",
    "crm": "CRM systems",
    "salesforce": "Salesforce",
    "sage": "Sage",
    "xero": "Xero",
    "quickbooks": "QuickBooks",
}

# =============================================================================
# ROLE TO SKILLS — maps job title / role mentions → list of implied skills
# Used by deterministic extractor to expand role names into skill signals.
# All keys MUST be lowercase.
# =============================================================================

ROLE_TO_SKILLS: dict[str, list[str]] = {
    "plant operator": ["plant operation", "health and safety", "construction labour"],
    "plant operative": ["plant operation", "health and safety", "construction labour"],
    "heavy plant operator": ["plant operation", "health and safety", "construction labour"],
    "labourer": ["construction labour", "manual handling", "health and safety"],
    "laborer": ["construction labour", "manual handling", "health and safety"],
    "general labourer": ["construction labour", "manual handling", "health and safety"],
    "construction labourer": ["construction labour", "manual handling", "health and safety"],
    "bricklayer": ["bricklaying", "construction labour", "health and safety"],
    "plasterer": ["plastering", "construction labour"],
    "carpenter": ["carpentry", "construction labour"],
    "joiner": ["joinery", "construction labour"],
    "scaffolder": ["scaffolding", "working at heights", "health and safety"],
    "roofer": ["roofing", "working at heights", "health and safety"],
    "tiler": ["tiling", "construction labour"],
    "painter": ["painting and decorating"],
    "decorator": ["painting and decorating"],
    "welder": ["welding", "health and safety"],
    "groundworker": ["groundwork", "construction labour"],
    "electrician": ["electrical work", "health and safety"],
    "plumber": ["plumbing", "health and safety"],
    "site manager": ["site management", "health and safety", "site supervision"],
    "site supervisor": ["site supervision", "health and safety"],
    "forklift operator": ["forklift operation", "health and safety"],
    "warehouse operative": ["warehouse operations", "manual handling"],
    "warehouse worker": ["warehouse operations", "manual handling"],
    "machine operator": ["machine operation", "health and safety"],
    "machine operative": ["machine operation", "health and safety"],
    "cnc operator": ["CNC operation", "machine operation"],
    "cnc machinist": ["CNC operation", "machine operation"],
    "delivery driver": ["delivery driving", "driving licence"],
    "van driver": ["van driving", "driving licence"],
    "hgv driver": ["HGV licence", "driving licence"],
    "lgv driver": ["LGV driving", "driving licence"],
    # ── Mechanics / Automotive (English) ──────────────────────────────────
    "mechanic": ["vehicle diagnostics", "vehicle servicing", "fault finding", "engine repair"],
    "vehicle technician": ["vehicle diagnostics", "vehicle servicing", "fault finding", "engine repair"],
    "automotive mechanic": ["vehicle diagnostics", "vehicle servicing", "fault finding", "engine repair"],
    "automotive technician": ["vehicle diagnostics", "vehicle servicing", "fault finding"],
    "auto mechanic": ["vehicle diagnostics", "vehicle servicing", "fault finding", "engine repair"],
    "car mechanic": ["vehicle diagnostics", "vehicle servicing", "fault finding", "engine repair"],
    "motor mechanic": ["vehicle diagnostics", "vehicle servicing", "fault finding", "engine repair"],
    "motor vehicle technician": ["vehicle diagnostics", "vehicle servicing", "fault finding"],
    "light vehicle technician": ["vehicle diagnostics", "vehicle servicing", "tyre fitting"],
    "heavy vehicle technician": ["vehicle diagnostics", "vehicle servicing", "engine repair"],
    "mot tester": ["MOT testing", "vehicle inspection"],
    # ── Mechanics / Automotive (Polish) ───────────────────────────────────
    "mechanik": ["vehicle diagnostics", "vehicle servicing", "fault finding", "engine repair"],
    "mechanik samochodowy": ["vehicle diagnostics", "vehicle servicing", "fault finding", "engine repair"],
    "mechanik pojazdów": ["vehicle diagnostics", "vehicle servicing", "fault finding", "engine repair"],
    "mechanik pojazdów samochodowych": ["vehicle diagnostics", "vehicle servicing", "fault finding", "engine repair", "vehicle inspection"],
    "technik mechanik": ["vehicle diagnostics", "vehicle servicing", "engine repair"],
    "technik pojazdów samochodowych": ["vehicle diagnostics", "vehicle servicing", "engine repair", "vehicle inspection"],
    # ── Construction (Polish) ─────────────────────────────────────────────
    "budowlaniec": ["construction labour", "manual handling", "health and safety"],
    "pracownik budowlany": ["construction labour", "manual handling", "health and safety"],
    "robotnik budowlany": ["construction labour", "manual handling"],
    "murarz": ["bricklaying", "construction labour", "health and safety"],
    "tynkarz": ["plastering", "construction labour"],
    "cieśla": ["carpentry", "construction labour"],
    "stolarz": ["joinery", "construction labour"],
    "spawacz": ["welding", "health and safety"],
    "elektryk": ["electrical work", "health and safety"],
    "hydraulik": ["plumbing", "health and safety"],
    "dekarz": ["roofing", "working at heights", "health and safety"],
    "glazurnik": ["tiling", "construction labour"],
    "malarz": ["painting and decorating"],
    # ── Warehouse (Polish) ────────────────────────────────────────────────
    "magazynier": ["warehouse operations", "manual handling", "stock control", "order picking"],
    "pracownik magazynu": ["warehouse operations", "manual handling", "stock control"],
    "pracownik magazynowy": ["warehouse operations", "manual handling"],
    # ── Sales / Retail ────────────────────────────────────────────────────
    "sales assistant": ["sales", "customer service", "retail operations"],
    "retail assistant": ["retail operations", "customer service", "cash handling"],
    "customer service advisor": ["customer service", "complaint handling"],
    "customer service representative": ["customer service", "complaint handling"],
    "administrator": ["data entry", "Microsoft Office", "scheduling"],
    "admin assistant": ["data entry", "Microsoft Office", "filing"],
    "receptionist": ["customer service", "scheduling", "Microsoft Office"],
    "accounts assistant": ["bookkeeping", "Microsoft Excel", "data entry"],
    "hr assistant": ["HR administration", "recruitment", "Microsoft Office"],
}

# =============================================================================
# EXPERIENCE PATTERNS — regex patterns that map descriptive phrases → skills
# Each entry: (compiled_regex, canonical_skill)
# =============================================================================

import re as _re

EXPERIENCE_PATTERNS: list[tuple] = [
    # Construction — working at heights
    (_re.compile(r"\bwork(?:ed|ing)?\s+at\s+height", _re.I), "working at heights"),
    (_re.compile(r"\bheight\s+safety\b", _re.I), "working at heights"),
    # Construction — health and safety
    (_re.compile(r"\bhealth\s+(?:and|&)\s+safety\b", _re.I), "health and safety"),
    (_re.compile(r"\bh\s*&\s*s\b", _re.I), "health and safety"),
    (_re.compile(r"\bsite\s+safety\b", _re.I), "health and safety"),
    # Construction — CPCS
    (_re.compile(r"\bcpcs\b", _re.I), "CPCS certification"),
    (_re.compile(r"\bconstruction\s+plant\s+competence\b", _re.I), "CPCS certification"),
    # Construction — CSCS
    (_re.compile(r"\bcscs\b", _re.I), "CSCS card"),
    # Construction — manual handling
    (_re.compile(r"\bmanual\s+handling\b", _re.I), "manual handling"),
    # Construction — first aid
    (_re.compile(r"\bfirst\s+aid\b", _re.I), "first aid"),
    # Construction — plant / machinery
    (_re.compile(r"\bplant\s+(?:operator|operative|operation|machinery)\b", _re.I), "plant operation"),
    (_re.compile(r"\bheavy\s+(?:plant|machinery)\b", _re.I), "plant operation"),
    (_re.compile(r"\boperat(?:ed|ing|es?)\s+(?:plant|machinery|equipment)\b", _re.I), "plant operation"),
    # Construction — assisted trades
    (_re.compile(r"\bassist(?:ed|ing)?\s+electrician", _re.I), "electrical work support"),
    (_re.compile(r"\bassist(?:ed|ing)?\s+plumber", _re.I), "plumbing support"),
    (_re.compile(r"\bassist(?:ed|ing)?\s+joiner", _re.I), "joinery support"),
    (_re.compile(r"\bassist(?:ed|ing)?\s+carpenter", _re.I), "carpentry"),
    (_re.compile(r"\bassist(?:ed|ing)?\s+welder", _re.I), "welding"),
    # Construction — projects
    (_re.compile(r"\bconstruction\s+project", _re.I), "construction project experience"),
    (_re.compile(r"\bwork(?:ed|ing)?\s+on\s+(?:construction|building|site)\s+project", _re.I), "construction project experience"),
    # Driving
    (_re.compile(r"\bdriving\s+licen[cs]e?\b", _re.I), "driving licence"),
    (_re.compile(r"\bdriver\s+licen[cs]e?\b", _re.I), "driving licence"),
    (_re.compile(r"\bfull\s+(?:uk\s+)?driving\s+licen[cs]e?\b", _re.I), "driving licence"),
    (_re.compile(r"\bclean\s+driving\s+licen[cs]e?\b", _re.I), "driving licence"),
    (_re.compile(r"\bhgv\s+licen[cs]e?\b", _re.I), "HGV licence"),
    (_re.compile(r"\blgv\s+licen[cs]e?\b", _re.I), "LGV driving"),
    # Forklift
    (_re.compile(r"\bforklift\b", _re.I), "forklift operation"),
    (_re.compile(r"\bfork\s*lift\b", _re.I), "forklift operation"),
    (_re.compile(r"\bfork\s*lift\s+truck\b", _re.I), "forklift operation"),
    # Warehouse
    (_re.compile(r"\bpick\s+(?:and|&)\s+pack\b", _re.I), "pick and pack"),
    (_re.compile(r"\bpicking\s+(?:and|&)\s+packing\b", _re.I), "pick and pack"),
    (_re.compile(r"\brf\s+(?:gun|scanner|scanning)\b", _re.I), "RF scanning"),
    (_re.compile(r"\bstock\s+(?:control|management|take|taking)\b", _re.I), "stock control"),
    (_re.compile(r"\binventory\s+(?:control|management)\b", _re.I), "inventory management"),
    # Retail
    (_re.compile(r"\bcash\s+handling\b", _re.I), "cash handling"),
    (_re.compile(r"\bcustomer\s+(?:service|support|care)\b", _re.I), "customer service"),
    (_re.compile(r"\bcomplaint\s+handling\b", _re.I), "complaint handling"),
    (_re.compile(r"\bhandling\s+complaints\b", _re.I), "complaint handling"),
    # Manufacturing
    (_re.compile(r"\bquality\s+control\b", _re.I), "quality control"),
    (_re.compile(r"\bquality\s+assurance\b", _re.I), "quality assurance"),
    (_re.compile(r"\blean\s+manufacturing\b", _re.I), "lean manufacturing"),
    (_re.compile(r"\bsix\s+sigma\b", _re.I), "Six Sigma"),
    (_re.compile(r"\bproduction\s+line\b", _re.I), "assembly line"),
    (_re.compile(r"\bassembly\s+line\b", _re.I), "assembly line"),
    # Mechanics
    (_re.compile(r"\bvehicle\s+diagnostic", _re.I), "vehicle diagnostics"),
    (_re.compile(r"\bmot\s+test", _re.I), "MOT testing"),
    (_re.compile(r"\bbrake\s+(?:system|repair|work)\b", _re.I), "brake system repair"),
    (_re.compile(r"\bengine\s+(?:repair|work|overhaul)\b", _re.I), "engine repair"),
    (_re.compile(r"\bvehicle\s+servic", _re.I), "vehicle servicing"),
    (_re.compile(r"\bfault\s+(?:finding|diagnosis|diagnostic)\b", _re.I), "fault finding"),
    # Admin / Office
    (_re.compile(r"\bmicrosoft\s+office\b", _re.I), "Microsoft Office"),
    (_re.compile(r"\bms\s+office\b", _re.I), "Microsoft Office"),
    (_re.compile(r"\bdata\s+entry\b", _re.I), "data entry"),
    (_re.compile(r"\bproject\s+management\b", _re.I), "project management"),
    (_re.compile(r"\bgdpr\b", _re.I), "GDPR compliance"),
    (_re.compile(r"\bpayroll\b", _re.I), "payroll"),
    (_re.compile(r"\bbookkeeping\b", _re.I), "bookkeeping"),
    (_re.compile(r"\bbook\s+keeping\b", _re.I), "bookkeeping"),
    # ── Polish — Mechanics / Automotive ───────────────────────────────────
    (_re.compile(r"\bmechanik\b", _re.I), "vehicle servicing"),
    (_re.compile(r"\bmechanik\s+samochodow", _re.I), "vehicle servicing"),
    (_re.compile(r"\bmechanik\s+pojazd", _re.I), "vehicle servicing"),
    (_re.compile(r"\btechnik\s+pojazd", _re.I), "vehicle servicing"),
    (_re.compile(r"\bnaprawa\s+(?:aut|samochodów|samochodow|pojazdów|pojazdow)\b", _re.I), "engine repair"),
    (_re.compile(r"\bnaprawa\s+silnik", _re.I), "engine repair"),
    (_re.compile(r"\bdiagnostyka\b", _re.I), "vehicle diagnostics"),
    (_re.compile(r"\bdiagnostyka\s+(?:auta|pojazdu|pojazdów|samochodowa|komputerowa)\b", _re.I), "vehicle diagnostics"),
    (_re.compile(r"\bserwis\s+samochodow", _re.I), "vehicle servicing"),
    (_re.compile(r"\bserwis\s+pojazd", _re.I), "vehicle servicing"),
    (_re.compile(r"\bprzegl[aą]d\s+techniczny\b", _re.I), "vehicle inspection"),
    (_re.compile(r"\bwymiana\s+oleju\b", _re.I), "oil change"),
    (_re.compile(r"\bhamulce\b", _re.I), "brake system repair"),
    (_re.compile(r"\bukład\s+hamulcowy\b", _re.I), "brake system repair"),
    (_re.compile(r"\bskrzynia\s+bieg", _re.I), "transmission repair"),
    (_re.compile(r"\bblacharstwo\b", _re.I), "bodywork repair"),
    (_re.compile(r"\blakiernictwo\b", _re.I), "bodywork repair"),
    (_re.compile(r"\bwulkanizacja\b", _re.I), "tyre fitting"),
    (_re.compile(r"\bwymiana\s+opon\b", _re.I), "tyre fitting"),
    (_re.compile(r"\bgeometria\s+k[oó][łl]\b", _re.I), "wheel alignment"),
    # ── Polish — Construction ──────────────────────────────────────────────
    (_re.compile(r"\bprac[ae]\s+(?:na\s+)?budow", _re.I), "construction labour"),
    (_re.compile(r"\broboty\s+budowlane\b", _re.I), "construction labour"),
    (_re.compile(r"\bprac[ae]\s+fizyczn", _re.I), "manual handling"),
    (_re.compile(r"\bpraca\s+fizyczna\b", _re.I), "manual handling"),
    (_re.compile(r"\bprac[ae]\s+na\s+wysoko", _re.I), "working at heights"),
    (_re.compile(r"\bbhp\b", _re.I), "health and safety"),
    (_re.compile(r"\bbezpiecze[nń]stwo\s+(?:i\s+higiena|pracy)\b", _re.I), "health and safety"),
    (_re.compile(r"\bw[oó]zek\s+wid[łl]owy\b", _re.I), "forklift operation"),
    (_re.compile(r"\bobsługa\s+w[oó]zka\b", _re.I), "forklift operation"),
    (_re.compile(r"\bspawanie\b", _re.I), "welding"),
    (_re.compile(r"\bmurarstwo\b", _re.I), "bricklaying"),
    (_re.compile(r"\btynkowanie\b", _re.I), "plastering"),
    # ── Polish — Driving ──────────────────────────────────────────────────
    (_re.compile(r"\bprawo\s+jazdy\b", _re.I), "driving licence"),
    (_re.compile(r"\bprawo\s+jazdy\s+kat", _re.I), "driving licence"),
    # ── Polish — General ──────────────────────────────────────────────────
    (_re.compile(r"\bpierwsza\s+pomoc\b", _re.I), "first aid"),
    (_re.compile(r"\bobsługa\s+komputera\b", _re.I), "Microsoft Office"),
    (_re.compile(r"\bpakiet\s+office\b", _re.I), "Microsoft Office"),
    (_re.compile(r"\bmagazynier\b", _re.I), "warehouse operations"),
    (_re.compile(r"\bpracownik\s+magazyn", _re.I), "warehouse operations"),
    (_re.compile(r"\bkompletacja\s+zam[oó]wie[nń]\b", _re.I), "order picking"),
]
